version: '2'

services:
  app:
    image: 'test-spring:latest'
    build:
      context: .
    container_name: app
    ports:
      - "7005:7005"
    depends_on:
      - db
    environment:
      - SERVER_PORT=7005
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_ADDRESS=db
      - DATABASE_NAME=test_db

  db:
    image: 'postgres:14.1'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db